### ISSUE TITLE
Implement faster way of getting largest token balances for WithdrawService

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/contracts#1]
Currently, the withdraw script creates a list of traded tokens (which is persisted to disk) and then queries them 1 by 1 (capped at a maximum of 200) to decide which ones of them to dump and convert (based on some min-value threshold).

Given current ETH and the distribution of tokens in the settlement contract it usually only makes sense to withdraw a few tokens with large balances. However, this may require running the script multiple times (8x at the current traded token list) in order to cover all traded tokens.

Maybe we can use an external service to quickly give us an overview of tokens held in the settlement contract ordered by $ value to speed up the script and make it complete in one pass.

I didn't do much research yet on which services offer such an API. Maybe the [zerion portfolio API](https://docs.zerion.io/websockets/getting-started/example) could be a good starting point

> Original issue https://github.com/gnosis/gp-v2-contracts/issues/930 by @fleupold

**Comment by chebii2** [comment]
Having this issue with my withdrawal. Missing total trades. Error when trying to scan QR code.. any other way to do it ?

**Comment by nlordell** [comment]
Hey @chebii2, sorry to hear that?

Do you mind elaborating a bit more on what you are having issues with? There are no "deposits" in CoW Swap, so you shouldn't need to withdraw anything 🤔. Also I'm not sure exactly what QR code you are referring to (there should be no QR codes involved in fee withdrawal).

This GitHub issue is specifically for withdrawing accrued fees for [solvers](https://docs.cow.fi/off-chain-services/solvers) and is meant as a back-end infrastructure piece and not for CoW Swap users.

**Comment by nlordell** [comment]
Sure. It might help me understand what problem you are facing.

**Comment by mfw78** [comment]
Recently with the advent of [`cow-fee`](https://github.com/cowdao-grants/cow-fee), we've opted for indexing on `Trade` events with a lookback period to determine recently traded tokens which then have a quote generated by the API, determining if they're of a minimum balance.
