### ISSUE TITLE
chore: rename to `contracts-core`

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#108]

**Comment by fedgiac** [comment]
Renaming this repo means renaming the implicit Foundry package defined by this repo. In particular, all projects that import these contracts are going to break. This reason by itself would be enough for me to reconsider the name change.

**Comment by fedgiac** [comment]
I want to stress this point with an actual example from an existing repo: [cowprotocol/composable-cow](https://github.com/cowprotocol/composable-cow).
Commit [24d556b634e21065e0ee70dd27469a6e699a8998](https://github.com/cowprotocol/composable-cow/commit/24d556b634e21065e0ee70dd27469a6e699a8998) changed the import of this repo from `rndlabs/cowswap-contracts` to `cowprotocol/contracts` (and corresponding deletion of the repo `rndlabs/cowswap-contracts`).

This was locally painful to manage for a user who didn't perform this migration but just pulled new changes to `composable-cow` from `origin`: for whatever reason, the submodule origin was still kept to `rndlabs/cowswap-contracts` and I couldn't find any simple incantation with `forge ...` or `git submodule ...` that would just pick up the submodule (i.e., dependency) URL change and would update it in the local repo. For example, `forge install` would error out by first still trying to fetch `rndlabs/cowswap-contracts` (which would return a not-found error and thus ask for GitHub credentials in the hope it was a private repo) and then it failed when the repo wasn't found. Other things I tried are variations of `forge update`, `git submodule update`, `git reset`, `git submodule deinit`, and removing folders like `.git/modules/lib/cowprotocol`, `lib/`, ...

What worked was managing the git submodule by hand to reach the desired commit:
```
cd lib/cowprotocol/ # path to the local import of this repo
git remote remove origin
git remote add origin 'https://github.com/cowprotocol/contracts' # latest URL of the repo 
git fetch
git checkout a10f40788af29467e87de3dbf2196662b0a6b500 # this is the commit of the dependency in lib/cowprotocol at the time of writing
```

Overall, a tedious and atypical debugging issue that I wouldn't want to impose on all people who rely on `cowprotocol/contracts` unless there's a strong reason for this.

**Comment by mfw78** [comment]
Let's leave it as is.
