### ISSUE TITLE
Add Goerli to the networks.json file

### ISSUE THREAD

**Issue by nenadV91** [cowprotocol/contracts#11]
We created a [PR](https://github.com/cowprotocol/cowswap/pull/559) on the FE for the Goerli network implementation but seems like we need to do some stuff on the BE side and then to add the Goerli addresses to this file https://github.com/cowprotocol/contracts/blob/main/networks.json such as GPv2Settlement and GPv2VaultRelayer etc...

So in total we would need the following things 

https://barn.api.cow.fi/goerli/api
https://api.cow.fi/goerli/api
https://safe-transaction.goerli.gnosis.io (is this already working?)
https://safe-relay.goerli.gnosis.io/api/v1/gas-station/ (is this already working?)

GP_SETTLEMENT_CONTRACT_ADDRESS
GP_VAULT_RELAYER
V_COW_CONTRACT_ADDRESS
COW_CONTRACT_ADDRESS
GNO address

For locked GNO
MERKLE_DROP_CONTRACT_ADDRESSES
TOKEN_DISTRO_CONTRACT_ADDRESSES

**Comment by fedgiac** [comment]
All contracts in this repo have been deployed to Görli, the addresses are the same as on mainnet (see #13). This should be all the code changes required from this repository.

This means:
```sh
GP_SETTLEMENT_CONTRACT_ADDRESS="0x9008d19f58aabd9ed0d60971565aa8510560ab41"
GP_VAULT_RELAYER="0xC92E8bdf79f0507f65a392b0ab4667716BFE0110"
```

I opened an issue on the token repo to track the progress on deploying COW and vCOW tokens here: https://github.com/cowprotocol/token/issues/2. Comments on how this should be handled (e.g., how/to whom the token is distributed) are welcome.

For the APIs, progress is tracked here: https://github.com/cowprotocol/services/issues/155.

There are some contracts that aren't tracked by a repo controlled by us, namely:
 - GNO address
   I believe there is no Gnosis-sanctioned GNO address on Görli. Note that this address must be consistent with the infrastructure for locked GNO discussed next.
 - MERKLE_DROP_CONTRACT_ADDRESSES, TOKEN_DISTRO_CONTRACT_ADDRESSES
   This would probably be handled by the team who handled the testing for locked GNO. How does it work currently on Rinkeby @nenadV91? It would probably be complex to set up the whole infrastructure of their contracts by ourselves, and they might be already have a test version of the contract.

**Comment by anxolin** [comment]
> I believe there is no Gnosis-sanctioned GNO address on Görli. Note that this address must be consistent with the infrastructure for locked GNO discussed next.

I think we can do a new deployment with this https://github.com/gnosis/gno-token, mint a lot of GNO and send us some.
At least this is what we've done in the past for Kovan and Rinkeby

**Comment by anxolin** [comment]
> MERKLE_DROP_CONTRACT_ADDRESSES, TOKEN_DISTRO_CONTRACT_ADDRESSES
This would probably be handled by the team who handled the testing for locked GNO. How does it work currently on Rinkeby @nenadV91? It would probably be complex to set up the whole infrastructure of their contracts by ourselves, and they might be already have a test version of the contract.

@nenadV91 can we just not have this feature in this network? Only if we deprecate Rinkeby we should put some effort to it

**Comment by fedgiac** [comment]
Closing as CoW Swap is now available on Görli.
