### ISSUE TITLE
tests(e2e): `balancerSwap`

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#133]
May be implemented as a fork test.

**Comment by MukulKolpe** [comment]
Hey @mfw78, can I work on this one?

**Comment by mfw78** [comment]
Sure, if you wish. Please actively ensure you are rebasing on main regularly as there are many commits coming in :slightly_smiling_face:

**Comment by mfw78** [comment]
@MukulKolpe is there any update to this?

**Comment by mfw78** [comment]
Closed by #224
