### ISSUE TITLE
Dump script errors on token that is same as "to-token"

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/contracts#20]
```
Processing steps 1 to 5 of 32...
/home/e/contracts/src/ts/api.ts:142
    const error: CallError = new Error(
                             ^
Error: Calling "https://barn.api.cow.fi/mainnet/api/v1/markets/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/sell/1394156490525603742 undefined failed with 400: {"errorType":"SameBuyAndSellToken","description":"Buy token is the same as the sell token."}
    at call (/home/e/contracts/src/ts/api.ts:142:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async estimateTradeAmount (/home/e/contracts/src/ts/api.ts:164:44)
    at async ethValue (/home/e/contracts/src/tasks/ts/value.ts:80:10)
    at async Promise.all (index 2)
    at async getTransferToReceiver (/home/e/contracts/src/tasks/dump.ts:150:34)
```

This is because my token list contains weth and my `--to-token` is also weth. I'm not sure if I am supposed to manually remove Weth or if the script is supposed to handle it. Nic said that the script had done this in the past.

**Comment by fedgiac** [comment]
Thanks for the report, I created a PR that fixes this.

I also think this was a working feature in the past. Can it be that the api used to return a valid trade if selling WETH for WETH (same token, with the same amounts for sell and buy)? Maybe it used to assume that the trade can be achieved with no actual transaction (note: no receiver is involved).

Another point that might be interesting to mention: currently, the API returns `SameBuyAndSellToken` if selling WETH for ETH, which is a bit confusing.
