### ISSUE TITLE
Withdraw Script Not Working with DAI token

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/contracts#33]
Specifically, it looks like we are trying to estimate USD prices, but can't estimate for DAI because:
```
Warning: price retrieval failed for token DAI (0x6b175474e89094c44da98b954eedeac495271d0f): SameBuyAndSellToken (Buy token is the same as the sell token.)
```

**Comment by mfw78** [comment]
No longer an issue, but am tracking [withdrawing the target token](https://github.com/cowdao-grants/cow-fee/issues/23) (`WETH`) without a swap.
