### ISSUE TITLE
Verify xDai deployments on BlockScout

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/contracts#4]
:point_up: 

> Original issue https://github.com/gnosis/gp-v2-contracts/issues/340 by @nlordell

**Comment by fedgiac** [comment]
The main contracts were verified by external parties on blockscout, so I suppose the issue there was fixed.

I was also able to [verify the vault relayer](https://blockscout.com/xdai/mainnet/address/0xC92E8bdf79f0507f65a392b0ab4667716BFE0110/contracts#address-tabs). A broad description of how I did it follows.
1. `yarn add --dev '@nomiclabs/hardhat-etherscan'`
2. Add `import "@nomiclabs/hardhat-etherscan";` to the top of `hardhat.config.ts`.
3. Add the following the the exported object in `hardhat.config.ts` (yes, any api key works):
    ```
    etherscan: {
        apiKey: {
          xdai: "your API key",
        },
      },
    ```
4. Profit!
