### ISSUE TITLE
No safeApprove function in GPv2SafeERC20

### ISSUE THREAD

**Issue by miguelmtzinf** [cowprotocol/contracts#55]
I wonder why GPv2SafeERC20 library does not contain a `safeApprove` function that allows to call non-standard `approve` functions with no return value (e.g. USDT).

[OpenZeppelin's SafeERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol#L76) lib replaced the old `safeApprove` (which resets the allowance before updating it) with a new `forceApprove` to handle this specific case.

**Comment by nlordell** [comment]
> I wonder why GPv2SafeERC20 library does not contain a `safeApprove` function that allows to call non-standard `approve` functions with no return value (e.g. USDT).

We only implemented functions in the library that were needed for the CoW Protocol contracts. Since we do not make use of `approve` in our contracts, we didn't write the code for it (as the `GPv2SafeERC20` was not intended as a general purpose "safe ERC20" library).

**Comment by miguelmtzinf** [comment]
Got it, thanks @nlordell for the insight!
